### ISSUE TITLE
Problem with setting up the bundle 

### ISSUE THREAD

**Issue by ahmednaguib** [M6Web/KafkaBundle#10]
```
[RuntimeException]
    An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\DependencyInjection\Definition
  ::setFactory() in /vagrant/kafka/vendor/m6web/kafka-bundle/DependencyInjection/M6WebKafkaExtension.php:54
  Stack trace:
  #0 /vagrant/kafka/vendor/m6web/kafka-bundle/DependencyInjection/M6WebKafkaExtension.php(32): M6Web\Bundle\Ka
  fkaBundle\DependencyInjection\M6WebKafkaExtension->loadProducers(Object(Symfony\Component\DependencyInjecti
  on\ContainerBuilder), Array)
  #1 /vagrant/kafka/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionCo
  nfigurationPass.php(50): M6Web\Bundle\KafkaBundle\DependencyInjection\M6WebKafkaExtension->load(Array, Obje
  ct(Symfony\Component\DependencyInjection\ContainerBuilder))
  #2 /vagrant/kafka/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtension
  ConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->
  process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
  #3 /vagrant/xr in /vagrant/kafka/vendor/m6web/kafka-bundle/DependencyInjection/M6WebKafkaExtension.php on li
  ne 54 
```

I am using the same config as in the example.

**Comment by Oliboy50** [comment]
@ahmednaguib hello, could you tell us what is your symfony version (or dependency injection component version) ?

**Comment by ahmednaguib** [comment]
the app is running with symfony 2.5. Do you think it's the symfony version ?

**Comment by Fabex** [comment]
Hi, 
Yes I think that setFactory method was implemented in SF 2.7 or 2.8

**Comment by NastasiaSaby** [comment]
We have never tested it with Symfony 2.5. So yes it could be the problem.

**Comment by Oliboy50** [comment]
@ahmednaguib `Definition::setFactory()` was introduced in [symfony 2.6](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/DependencyInjection/Definition.php#L67)

so yes, this is the issue you're falling in :/ sorry

**Comment by Oliboy50** [comment]
@ahmednaguib sorry again, I think we won't be able to help you further with this issue, I suggest you to upgrade to symfony 2.6, which shouldn't be too painful

thanks for reporting this, we'll fix the minimum requirements => https://github.com/M6Web/KafkaBundle/pull/11

**Comment by ahmednaguib** [comment]
I will try to upgrade. It shouldn't be a problem. Thanks guys for the help.

**Comment by omansour** [comment]
we should require symfony => 2.6 so ?

**Comment by NastasiaSaby** [comment]
@omansour there's a PR here: https://github.com/M6Web/KafkaBundle/pull/11
